### ISSUE TITLE
not building for windows properely

### ISSUE THREAD

**Issue by SliderOnTheBlack** [radeeyate/ember#1]
I get this when running 'go build .'

PS C:\Users\xxx\ember> go build .
package ember
        imports fyne.io/fyne/v2/app
        imports fyne.io/fyne/v2/internal/driver/glfw
        imports fyne.io/fyne/v2/internal/driver/common
        imports fyne.io/fyne/v2/internal/painter/gl
        imports github.com/go-gl/gl/v2.1/gl: build constraints exclude all Go files in C:\Users\xxx\go\pkg\mod\github.com\go-gl\gl@v0.0.0-20211210172815-726fda9656d6\v2.1\gl

i might be dumb but I cant figure it out

**Comment by SliderOnTheBlack** [comment]
maybe you could release an an .exe for dumb people who cant compile for some reason like me

**Comment by radeeyate** [comment]
I can build an exe for Windows tomorrow, but for now, trying following the steps [here](https://docs.fyne.io/started/) and [here](https://docs.fyne.io/started/packaging).

**Comment by SliderOnTheBlack** [comment]
> I can build an exe for Windows tomorrow, but for now, trying following the steps [here](https://docs.fyne.io/started/) and [here](https://docs.fyne.io/started/packaging).

Thank you!

**Comment by SliderOnTheBlack** [comment]
I did get it to compile, but only on VS code for some reason? anyway, thank you for the help.
